#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
sudo apt-get update
sudo apt-get upgrade -y
sudo apt install haproxy -y
sudo echo "ENABLED-=1" >> /etc/default/haproxy
sudo echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back
backend http_back
        balance roundrobin
        server 34237-web-01 18.206.214.193:80 check
        server 34237-web-02 54.89.30.22:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
