#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend atomicabdul4life
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
   34237-web-01  18.206.214.193:80 check
   34237-web-02  54.89.30.22:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
